services:
    php:
        container_name: '${DOCKER_PREFIX_NAME}-php'
        build:
            context: ./compose/8.2
            dockerfile: Dockerfile
            args:
                - 'UID=${UID:-1000}'
                - 'GID=${GID:-1000}'
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - "${DOCKER_PHP_PORT:-9000}:9000"
        volumes:
            - './src:/var/www/html'
        networks:
            - local
    nginx:
        container_name: '${DOCKER_PREFIX_NAME}-nginx'
        build:
            context: ./compose/nginx
            dockerfile: Dockerfile
            args:
                - 'UID=${UID:-1000}'
                - 'GID=${GID:-1000}'
        ports:
            - "${DOCKER_NGINX_PORT:-80}:80"
        volumes:
            - './src:/var/www/html'
        depends_on:
            - php
        networks:
            - local

networks:
    local:
        driver: bridge
